import Foundation
import SwiftUI
import UIKit

struct AppTheme { static let background = Color(uiColor: UIColor { $0.userInterfaceStyle == .dark ? UIColor(red: 0.025, green: 0.040, blue: 0.032, alpha: 1) : UIColor(red: 0.965, green: 0.980, blue: 0.970, alpha: 1) }); static let primary = Color(uiColor: UIColor { $0.userInterfaceStyle == .dark ? .white : UIColor(red: 0.055, green: 0.095, blue: 0.075, alpha: 1) }); static let secondary = Color(uiColor: UIColor { $0.userInterfaceStyle == .dark ? UIColor(red: 0.64, green: 0.70, blue: 0.66, alpha: 1) : UIColor(red: 0.32, green: 0.39, blue: 0.35, alpha: 1) }); static let green = Color(uiColor: UIColor { $0.userInterfaceStyle == .dark ? UIColor(red: 0.18, green: 0.92, blue: 0.50, alpha: 1) : UIColor(red: 0.00, green: 0.45, blue: 0.25, alpha: 1) }); static let red = Color(uiColor: UIColor { $0.userInterfaceStyle == .dark ? UIColor(red: 1, green: 0.4, blue: 0.47, alpha: 1) : UIColor(red: 0.72, green: 0.08, blue: 0.13, alpha: 1) }); static let amber = Color(uiColor: UIColor { $0.userInterfaceStyle == .dark ? UIColor(red: 1, green: 0.75, blue: 0.3, alpha: 1) : UIColor(red: 0.58, green: 0.34, blue: 0, alpha: 1) }); static let missing = Color(uiColor: UIColor { $0.userInterfaceStyle == .dark ? UIColor(red: 0.17, green: 0.23, blue: 0.19, alpha: 1) : UIColor(red: 0.79, green: 0.84, blue: 0.81, alpha: 1) }); static let divider = Color(uiColor: UIColor { $0.userInterfaceStyle == .dark ? UIColor(red: 0.16, green: 0.23, blue: 0.18, alpha: 1) : UIColor(red: 0.70, green: 0.75, blue: 0.72, alpha: 1) }); static let monoTitle = Font.system(size: 20, weight: .bold, design: .monospaced); static let monoModel = Font.system(size: 17, weight: .bold, design: .monospaced); static let monoBody = Font.system(size: 14, design: .monospaced); static let monoMeta = Font.system(size: 11, design: .monospaced); static let monoSmall = Font.system(size: 10, design: .monospaced) }
func money(_ value: Double) -> String { String(format: "$%.2f", value) }
func clock(_ date: Date?) -> String { date?.formatted(date: .omitted, time: .shortened) ?? "--:--:--" }
func stateColor(_ state: ServiceState) -> Color { switch state { case .online: return AppTheme.green; case .stale: return AppTheme.amber; case .unknown: return AppTheme.secondary; default: return AppTheme.red } }
func stateText(_ state: ServiceState) -> String { switch state { case .online: return "正常"; case .offline: return "不可用"; case .misconfigured: return "未配置"; case .unauthorized: return "认证失败"; case .quotaExhausted: return "额度耗尽"; case .rateLimited: return "限流"; case .timeout: return "超时"; case .networkError: return "网络异常"; case .serverError: return "服务端异常"; case .clientError: return "请求异常"; case .stale: return "已过期"; case .unknown: return "未知" } }
