import SwiftUI
import UIKit

struct ContentView: View {
    @EnvironmentObject private var store: StatusStore
    @Environment(\.scenePhase) private var scenePhase
    @State private var showingSettings = false
    @State private var diagnosticsExpanded = true
    @State private var eventsExpanded = false
    @State private var selectedService: ServiceStatus?
    var body: some View {
        NavigationStack {
            ScrollView(showsIndicators: false) {
                VStack(alignment: .leading, spacing: 0) {
                    HeaderView(showingSettings: $showingSettings)
                    if let snapshot = store.snapshot {
                        GlobalHealthCard(snapshot: snapshot, store: store)
                        StatusOverview(snapshot: snapshot, store: store, selectedService: $selectedService)
                        DividerLine()
                        SubscriptionPanel(store: store, openSettings: { showingSettings = true })
                        ExtraPanels(snapshot: snapshot, store: store, diagnosticsExpanded: $diagnosticsExpanded, eventsExpanded: $eventsExpanded)
                        FooterView(snapshot: snapshot)
                    } else { LoadingView(message: store.lastError ?? "正在读取状态...") }
                }.padding(.horizontal, 22).padding(.top, 12).padding(.bottom, 28)
            }.background(AppTheme.background.ignoresSafeArea()).navigationBarHidden(true).refreshable { await store.refresh(source: "下拉刷新", forceSubscription: true) }
        }.sheet(isPresented: $showingSettings) { SettingsView(store: store) }.sheet(item: $selectedService) { ServiceDetailView(service: $0, store: store) }.sheet(item: $store.sharePayload) { payload in ActivityView(items: [payload.url]).presentationDetents([.medium]) }.onAppear { store.startForegroundLoop() }.onChange(of: scenePhase) { store.sceneChanged($0) }
    }
}
private struct HeaderView: View { @EnvironmentObject private var store: StatusStore; @Binding var showingSettings: Bool; var body: some View { HStack(alignment: .firstTextBaseline, spacing: 8) { Text("AI INPUT").font(AppTheme.monoTitle).foregroundColor(AppTheme.green); Spacer(); Text(store.gatewayLabel).font(AppTheme.monoBody).foregroundColor(store.snapshot?.gateway?.classification == .ok ? AppTheme.green : AppTheme.amber); Link(destination: gatewayEndpoint) { Image(systemName: "arrow.up.forward.app").foregroundColor(AppTheme.secondary).accessibilityLabel("打开状态 API") }; Button { showingSettings = true } label: { Image(systemName: "ellipsis").font(.title3).foregroundColor(AppTheme.secondary).frame(width: 28, height: 28) }.buttonStyle(.plain).accessibilityLabel("设置") } } }
private struct GlobalHealthCard: View { let snapshot: StatusSnapshot; @ObservedObject var store: StatusStore; var body: some View { let total = snapshot.services.count; let healthy = store.onlineCount; let issue = healthy < total || snapshot.gateway?.classification != .ok; VStack(alignment: .leading, spacing: 6) { HStack { Image(systemName: issue ? "exclamationmark.triangle.fill" : "checkmark.seal.fill").foregroundColor(issue ? AppTheme.red : AppTheme.green); Text(issue ? "服务存在异常" : "所有模型正常").font(.system(size: 18, weight: .bold)).foregroundColor(AppTheme.primary); Spacer(); Text("\(healthy)/\(total) 可用").font(AppTheme.monoBody).foregroundColor(issue ? AppTheme.red : AppTheme.green) }; Text(healthy < total ? "模型可用性异常 · 额度与订阅独立统计 · 数据 \(StatusEngine.dataTrustLabel(snapshot))" : "额度与订阅独立统计 · 最近更新 \(clock(snapshot.fetchedAt))").font(AppTheme.monoSmall).foregroundColor(AppTheme.secondary).fixedSize(horizontal: false, vertical: true); if let backup = snapshot.services.first(where: { StatusEngine.serviceState($0) == .online }), healthy < total { Text("建议临时切换到 \(backup.model)").font(AppTheme.monoSmall).foregroundColor(AppTheme.amber) } }.padding(12).background(AppTheme.divider.opacity(0.28)).clipShape(RoundedRectangle(cornerRadius: 10)).padding(.top, 14).accessibilityElement(children: .combine) } }
private struct StatusOverview: View { let snapshot: StatusSnapshot; @ObservedObject var store: StatusStore; @Binding var selectedService: ServiceStatus?; var body: some View { VStack(alignment: .leading, spacing: 0) { HStack { Text("\(store.historyRange.label) history · \(StatusEngine.dataTrustLabel(snapshot))").font(AppTheme.monoBody).foregroundColor(AppTheme.secondary); Spacer(); if store.isRefreshing { ProgressView().scaleEffect(0.65).tint(AppTheme.green) } }.padding(.top, 16).padding(.bottom, 7); HStack(spacing: 5) { Text("筛选").font(AppTheme.monoSmall).foregroundColor(AppTheme.secondary); ForEach(DiagnosticFilter.allCases) { filter in Button(filter.label) { store.diagnosticFilter = filter }.font(AppTheme.monoSmall).foregroundColor(store.diagnosticFilter == filter ? AppTheme.green : AppTheme.secondary) } }.padding(.bottom, 4); HStack(spacing: 5) { Text("分组").font(AppTheme.monoSmall).foregroundColor(AppTheme.secondary); ForEach(ServiceGrouping.allCases) { grouping in Button(grouping.label) { store.serviceGrouping = grouping }.font(AppTheme.monoSmall).foregroundColor(store.serviceGrouping == grouping ? AppTheme.green : AppTheme.secondary) } }.padding(.bottom, 6); ForEach(store.groupedServices, id: \.0) { group, services in if store.serviceGrouping != .model { Text(group).font(AppTheme.monoSmall).foregroundColor(AppTheme.amber) }; ForEach(services) { service in Button { selectedService = service } label: { ServicePanel(service: service, range: store.historyRange) }.buttonStyle(.plain).accessibilityLabel("查看 \(service.model) 详情") }; DividerLine().padding(.vertical, 5) }; HistoryRangePicker(selection: $store.historyRange).padding(.top, 5).padding(.bottom, 11) } } }
private struct HistoryRangePicker: View { @Binding var selection: HistoryRange; var body: some View { HStack { Text("历史窗口").font(AppTheme.monoMeta).foregroundColor(AppTheme.secondary); Spacer(); ForEach(HistoryRange.allCases, id: \.self) { range in Button(range.label) { selection = range }.font(AppTheme.monoMeta).foregroundColor(selection == range ? AppTheme.green : AppTheme.secondary) } } } }
private struct ServicePanel: View { let service: ServiceStatus; let range: HistoryRange; var body: some View { let state = StatusEngine.serviceState(service); let summary = StatusEngine.historySummary(service, range: range); let stats = StatusEngine.latencyStats(service, range: range); VStack(alignment: .leading, spacing: 4) { HStack { Text("→").foregroundColor(AppTheme.secondary); Text(service.model).font(AppTheme.monoModel).foregroundColor(AppTheme.primary); Circle().fill(stateColor(state)).frame(width: 8, height: 8); Text(stateText(state)).font(AppTheme.monoBody).foregroundColor(stateColor(state)); Spacer(); Text(service.last?.latencyMS.map { "\($0) ms" } ?? "--").font(AppTheme.monoMeta).foregroundColor(AppTheme.secondary) }; HStack { Text("可用率 \(pct(service.uptimePercent))"); Text("· \(range.label) \(pct(summary.successRate))"); Text("· \(summary.observed)/\(range.rawValue)") }.font(AppTheme.monoMeta).foregroundColor(AppTheme.secondary).padding(.leading, 29); HStack { if summary.missing > 0 { Text("缺失 \(summary.missing)m") }; if let p95 = stats.p95 { Text("· p95 \(p95) ms") } }.font(AppTheme.monoSmall).foregroundColor(AppTheme.secondary).padding(.leading, 29); LatencyTrend(service: service, range: range); HistoryBar(summary: summary) }.padding(.vertical, 3) }; private func pct(_ value: Double?) -> String { value.map { String(format: "%.1f%%", $0) } ?? "--" } }
private struct LatencyTrend: View { let service: ServiceStatus; let range: HistoryRange; var body: some View { let values = Array(service.history.filter { $0.ok == true }.compactMap(\.latencyMS).suffix(range.rawValue)); VStack(alignment: .leading, spacing: 2) { HStack { Text("延迟趋势").font(AppTheme.monoSmall).foregroundColor(AppTheme.secondary); Spacer(); if let p95 = RustCore.p95(values) { Text("p95 \(p95) ms").font(AppTheme.monoSmall).foregroundColor(AppTheme.secondary) } }; GeometryReader { geo in let maxValue = CGFloat(max(values.max() ?? 1, 1)); HStack(alignment: .bottom, spacing: 1) { ForEach(Array(values.enumerated()), id: \.offset) { _, value in RoundedRectangle(cornerRadius: 1).fill(AppTheme.green.opacity(0.7)).frame(height: max(2, geo.size.height * CGFloat(value) / maxValue)) } } }.frame(height: 22) }.accessibilityElement(children: .combine) } }
private struct HistoryBar: View { let summary: HistorySummary; var body: some View { GeometryReader { geo in let count = max(1, summary.slots.count); let gap: CGFloat = count > 120 ? 0.4 : 1; let width = max(1.2, (geo.size.width - gap * CGFloat(count - 1)) / CGFloat(count)); HStack(spacing: gap) { ForEach(Array(summary.slots.enumerated()), id: \.offset) { _, value in Capsule().fill(value == true ? AppTheme.green : value == false ? AppTheme.red : AppTheme.missing).frame(width: width, height: value == nil ? 7 : 15) } } }.frame(height: 15).accessibilityLabel("成功 \(summary.succeeded) 分钟，失败 \(summary.failed) 分钟，缺失 \(summary.missing) 分钟") } }
private struct SubscriptionPanel: View { @ObservedObject var store: StatusStore; let openSettings: () -> Void; var body: some View { let plans = SubscriptionEngine.sortedPlans(store.subscription?.plans ?? []).filter { $0.isActive() }; let summary = SubscriptionEngine.summary(plans); VStack(alignment: .leading, spacing: 7) { HStack { Text("订阅额度").font(.system(size: 21, weight: .bold)).foregroundColor(AppTheme.primary); Spacer(); Text(SubscriptionEngine.healthLabel(SubscriptionEngine.health(store.subscription, tokenConfigured: store.tokenConfigured, error: store.subscriptionError))).font(AppTheme.monoMeta).foregroundColor(AppTheme.amber) }.padding(.top, 19); if plans.isEmpty { HStack { Text(store.tokenConfigured ? "正在读取订阅额度" : "未配置订阅 Token").font(AppTheme.monoBody).foregroundColor(AppTheme.secondary); Spacer(); Button(store.tokenConfigured ? "刷新" : "配置", action: openSettings).foregroundColor(AppTheme.green) } } else { HStack { Text("今日总剩余").font(AppTheme.monoBody).foregroundColor(AppTheme.secondary); Spacer(); Text("\(money(summary.totalRemainingUSD)) / \(money(summary.totalLimitUSD))").font(.system(size: 20, weight: .bold, design: .monospaced)).foregroundColor(AppTheme.green) }; Text("\(summary.activePlans) 个有效套餐 · 上海 00:00 · \(SubscriptionEngine.freshnessLabel(store.subscription)) · 更新 \(clock(store.subscription?.fetchedAt))").font(AppTheme.monoSmall).foregroundColor(AppTheme.secondary); ForEach(plans) { PlanRow(plan: $0) } } } } }
private struct PlanRow: View { let plan: SubscriptionPlan; var body: some View { VStack(alignment: .leading, spacing: 4) { HStack { Image(systemName: "creditcard.fill").foregroundColor(AppTheme.green); Text(plan.name).font(.system(size: 18, weight: .bold)).foregroundColor(AppTheme.primary); Spacer(); Text("有效").font(AppTheme.monoBody).foregroundColor(AppTheme.green) }; HStack { Text("每日 \(money(plan.dailyUsageUSD)) / \(money(plan.dailyLimitUSD))").font(AppTheme.monoBody).foregroundColor(AppTheme.secondary); Spacer(); Text("剩余 \(money(plan.remainingUSD))").font(AppTheme.monoBody).bold().foregroundColor(AppTheme.green) }; ProgressBar(value: plan.usagePercent); HStack { Text("已用 \(String(format: "%.1f", plan.usagePercent))%"); Spacer(); Text(SubscriptionEngine.expiryLabel(plan.expiresAt)) }.font(AppTheme.monoMeta).foregroundColor(AppTheme.secondary); Text("本周 \(money(plan.weeklyUsageUSD)) · 本月 \(money(plan.monthlyUsageUSD))").font(AppTheme.monoSmall).foregroundColor(AppTheme.secondary); DividerLine() } } }
private struct ProgressBar: View { let value: Double; var body: some View { GeometryReader { geo in ZStack(alignment: .leading) { Capsule().fill(AppTheme.missing.opacity(0.52)); Capsule().fill(value >= 90 ? AppTheme.red : value >= 70 ? AppTheme.amber : AppTheme.green).frame(width: geo.size.width * min(100, max(0, value)) / 100) } }.frame(height: 6).accessibilityLabel("已使用 \(String(format: "%.1f", value))%") } }

private struct ExtraPanels: View { let snapshot: StatusSnapshot; @ObservedObject var store: StatusStore; @Binding var diagnosticsExpanded: Bool; @Binding var eventsExpanded: Bool; @State private var technical = Set<String>(); var body: some View { let diagnostics = StatusEngine.diagnostics(snapshot, settings: store.notificationSettings); if !diagnostics.isEmpty { DividerLine().padding(.top, 14); DisclosureGroup(isExpanded: $diagnosticsExpanded) { VStack(alignment: .leading, spacing: 10) { ForEach(diagnostics) { item in DiagnosticCard(item: item, expanded: technical.contains(item.id), toggle: { if technical.contains(item.id) { technical.remove(item.id) } else { technical.insert(item.id) } }, refresh: { Task { await store.refresh(source: "诊断修复", forceSubscription: true) } }) }; HStack(spacing: 12) { Button { store.copyDiagnosticReport() } label: { Label("复制诊断", systemImage: "doc.on.clipboard") }; Button { store.export(format: .json) } label: { Label("导出 JSON", systemImage: "square.and.arrow.up") }; Button { store.export(format: .csv) } label: { Label("导出 CSV", systemImage: "tablecells") } }.font(AppTheme.monoSmall).foregroundColor(AppTheme.green) }.padding(.top, 8) } label: { Text("诊断 · \(diagnostics.count) 项").font(.system(size: 18, weight: .bold)).foregroundColor(AppTheme.primary) }.tint(AppTheme.secondary).padding(.top, 14) }; let events = Array(StatusEngine.loadEvents().prefix(8)); if !events.isEmpty { DividerLine().padding(.top, 14); DisclosureGroup(isExpanded: $eventsExpanded) { VStack(alignment: .leading, spacing: 8) { ForEach(events) { event in HStack(alignment: .top, spacing: 8) { Image(systemName: event.phase == .opened ? "xmark.octagon.fill" : "checkmark.circle.fill").foregroundColor(event.phase == .opened ? AppTheme.red : AppTheme.green); VStack(alignment: .leading) { Text("\(event.target) · \(event.phase == .opened ? "异常" : "恢复")").font(AppTheme.monoBody).foregroundColor(AppTheme.primary); Text("\(event.detail) · \(clock(event.date))").font(AppTheme.monoSmall).foregroundColor(AppTheme.secondary) } } } }.padding(.top, 8) } label: { Text("最近异常事件").font(.system(size: 18, weight: .bold)).foregroundColor(AppTheme.primary) }.tint(AppTheme.secondary).padding(.top, 14) } } }
private struct DiagnosticCard: View { let item: DiagnosticItem; let expanded: Bool; let toggle: () -> Void; let refresh: () -> Void; var body: some View { HStack(alignment: .top, spacing: 8) { Image(systemName: item.severity == .failure ? "xmark.octagon.fill" : "exclamationmark.triangle.fill").foregroundColor(item.severity == .failure ? AppTheme.red : AppTheme.amber); VStack(alignment: .leading, spacing: 3) { Text(item.title).font(AppTheme.monoBody).foregroundColor(AppTheme.primary); Text(item.detail).font(AppTheme.monoSmall).foregroundColor(AppTheme.secondary).fixedSize(horizontal: false, vertical: true); HStack(spacing: 12) { Button("重新检测", action: refresh).font(AppTheme.monoSmall).foregroundColor(AppTheme.green); if item.technicalDetail != nil { Button(expanded ? "收起技术详情" : "技术详情", action: toggle).font(AppTheme.monoSmall).foregroundColor(AppTheme.secondary) } }; if expanded, let detail = item.technicalDetail { Text(detail).font(AppTheme.monoSmall).foregroundColor(AppTheme.amber).textSelection(.enabled) } } }.accessibilityElement(children: .contain) } }
private struct ServiceDetailView: View { let service: ServiceStatus; @ObservedObject var store: StatusStore; @Environment(\.dismiss) private var dismiss; var body: some View { NavigationStack { ScrollView { VStack(alignment: .leading, spacing: 14) { HStack { Circle().fill(stateColor(StatusEngine.serviceState(service))).frame(width: 10, height: 10); Text(stateText(StatusEngine.serviceState(service))).foregroundColor(stateColor(StatusEngine.serviceState(service))); Spacer(); Text(service.model).font(AppTheme.monoModel).foregroundColor(AppTheme.primary) }; DetailRow(title: "供应商", value: config?.provider ?? "Input"); DetailRow(title: "账号", value: config?.account ?? "默认账号"); DetailRow(title: "最后探测", value: clock(service.last?.timestamp)); let stats = StatusEngine.latencyStats(service, range: store.historyRange); DetailRow(title: "延迟", value: "min \(stats.minimum.map(String.init) ?? "--") · p50 \(stats.median.map(String.init) ?? "--") · p95 \(stats.p95.map(String.init) ?? "--") · max \(stats.maximum.map(String.init) ?? "--") ms"); if let error = service.last?.error { Text("当前错误").font(.headline).foregroundColor(AppTheme.primary); Text(error).font(AppTheme.monoSmall).foregroundColor(AppTheme.red).textSelection(.enabled) }; Button { store.copyDiagnosticReport() } label: { Label("复制诊断报告", systemImage: "doc.on.clipboard") }.foregroundColor(AppTheme.green) }.padding(22) }.background(AppTheme.background.ignoresSafeArea()).navigationTitle("模型 / 账号详情").navigationBarTitleDisplayMode(.inline).toolbar { ToolbarItem(placement: .navigationBarTrailing) { Button("完成") { dismiss() } } } } } ; private var config: ModelMonitor? { store.modelMonitors.first { $0.model == service.model } } }
private struct DetailRow: View { let title: String; let value: String; var body: some View { HStack { Text(title).font(AppTheme.monoBody).foregroundColor(AppTheme.secondary); Spacer(); Text(value).font(AppTheme.monoBody).foregroundColor(AppTheme.primary).multilineTextAlignment(.trailing) }.accessibilityElement(children: .combine) } }
private struct ActivityView: UIViewControllerRepresentable { let items: [Any]; func makeUIViewController(context: Context) -> UIActivityViewController { UIActivityViewController(activityItems: items, applicationActivities: nil) }; func updateUIViewController(_ controller: UIActivityViewController, context: Context) {} }
private struct FooterView: View { let snapshot: StatusSnapshot; var body: some View { VStack(alignment: .leading, spacing: 4) { DividerLine().padding(.top, 17); Text("data \(clock(snapshot.generatedAt)) · \(StatusEngine.dataTrustLabel(snapshot)) · 更新 \(clock(snapshot.fetchedAt))").font(AppTheme.monoSmall).foregroundColor(AppTheme.secondary).lineLimit(1).minimumScaleFactor(0.7); if let error = snapshot.lastError { Text(error).font(AppTheme.monoSmall).foregroundColor(AppTheme.amber) } } } }
private struct LoadingView: View { let message: String; var body: some View { VStack(alignment: .leading, spacing: 10) { ProgressView().tint(AppTheme.green); Text(message).font(AppTheme.monoBody).foregroundColor(AppTheme.secondary) }.padding(.top, 80) } }
private struct DividerLine: View { var body: some View { Rectangle().fill(AppTheme.divider).frame(height: 1) } }
