import SwiftUI
import UIKit

struct SettingsView: View {
    @ObservedObject var store: StatusStore
    @Environment(\.dismiss) private var dismiss
    var body: some View {
        NavigationStack { Form { subscriptionSection; modelSection; notificationSection; monitorSection; backendSection; eventsSection; aboutSection }.scrollContentBackground(.hidden).background(AppTheme.background).navigationTitle("设置").navigationBarTitleDisplayMode(.inline).toolbar { ToolbarItem(placement: .navigationBarTrailing) { Button("完成") { dismiss() }.foregroundColor(AppTheme.green) } } }
    }
    private var subscriptionSection: some View { Section { HStack { Image(systemName: "creditcard.fill").foregroundColor(AppTheme.green); Text(store.tokenConfigured ? "Token 已配置" : "未配置订阅 Token"); Spacer(); Text(store.subscription.map { SubscriptionEngine.healthLabel(SubscriptionEngine.health($0, tokenConfigured: store.tokenConfigured, error: store.subscriptionError)) } ?? "--").foregroundColor(AppTheme.secondary).font(.footnote) }; SecureField("粘贴 Bearer Token", text: $store.tokenDraft).textInputAutocapitalization(.never).autocorrectionDisabled(true); HStack { Button { store.pasteToken() } label: { Label("从剪贴板粘贴", systemImage: "doc.on.clipboard") }; Spacer(); Button { Task { await store.saveToken() } } label: { Label("保存并读取", systemImage: "arrow.down.circle") }.disabled(store.tokenDraft.isEmpty || store.subscriptionRefreshing) }; if store.tokenConfigured { HStack { Button { Task { await store.refreshSubscription() } } label: { Label("刷新额度", systemImage: "arrow.clockwise") }.disabled(store.subscriptionRefreshing); Spacer(); Button(role: .destructive) { store.removeToken() } label: { Label("删除 Token", systemImage: "key.slash") } } }; if let error = store.subscriptionError { Text(error).font(.footnote).foregroundColor(AppTheme.amber) }; Text("Token 仅保存于本机 Keychain；额度过期时会明确标注最后更新时间。").font(.footnote).foregroundColor(AppTheme.secondary) } header: { Text("订阅额度") } }
    private var modelSection: some View { Section { ForEach($store.modelMonitors) { $model in VStack(alignment: .leading, spacing: 7) { Toggle(isOn: $model.enabled) { Text(model.model).font(.headline) }; HStack { TextField("供应商", text: $model.provider); TextField("账号", text: $model.account) }; HStack { Button(model.isMuted ? "取消忽略" : "忽略 8 小时") { if model.isMuted { model.mutedUntil = nil; store.updateModelMonitors(store.modelMonitors) } else { store.muteModel(model) } }.font(.footnote).foregroundColor(AppTheme.green); Spacer(); if model.isInMaintenance { Text("维护中").font(.footnote).foregroundColor(AppTheme.amber) }; Button("维护 2 小时") { store.maintenanceModel(model); }.font(.footnote).foregroundColor(AppTheme.amber) } }.onChange(of: model) { _ in store.updateModelMonitors(store.modelMonitors) } }; Text("支持按供应商、账号、模型分组；忽略或维护中的模型不会触发异常通知。备用模型仅提供建议，不会擅自改变外部客户端配置。").font(.footnote).foregroundColor(AppTheme.secondary) } header: { Text("模型与账号") } }
    private var notificationSection: some View { Section { Toggle("状态异常提醒", isOn: boolBinding(\.enabled)); Toggle("恢复提醒", isOn: boolBinding(\.recoveryEnabled)); Toggle("网关延迟提醒", isOn: boolBinding(\.gatewayEnabled)); Toggle("每日额度提醒", isOn: boolBinding(\.subscriptionQuotaEnabled)); Toggle("订阅到期提醒", isOn: boolBinding(\.subscriptionExpiryEnabled)); Picker("连续失败阈值", selection: intBinding(\.failureMinutes)) { Text("2 分钟").tag(2); Text("5 分钟").tag(5); Text("10 分钟").tag(10) }; Picker("网关延迟阈值", selection: intBinding(\.gatewayThresholdMS)) { Text("1000 ms").tag(1000); Text("1500 ms").tag(1500); Text("3000 ms").tag(3000) }; Picker("额度提醒阈值", selection: intBinding(\.subscriptionQuotaThreshold)) { Text("70%").tag(70); Text("85%").tag(85); Text("95%").tag(95) }; Button { Task { await store.requestNotificationPermission() } } label: { Label("请求系统通知权限", systemImage: "bell.badge") } } header: { Text("通知") } footer: { Text("连续失败达到阈值时提醒；服务恢复时发送恢复通知。") } }
    private var monitorSection: some View { Section { ForEach($store.monitors) { $monitor in VStack(alignment: .leading, spacing: 8) { Toggle(isOn: $monitor.enabled) { Text(monitor.label.isEmpty ? "新监测目标" : monitor.label) }; TextField("显示名称", text: $monitor.label); TextField("https://example.com", text: $monitor.url).textInputAutocapitalization(.never).autocorrectionDisabled(true); Picker("延迟阈值", selection: $monitor.thresholdMS) { Text("1000 ms").tag(1000); Text("1500 ms").tag(1500); Text("3000 ms").tag(3000) }; if !monitor.url.isEmpty && !StatusEngine.validateMonitorURL(monitor.url) { Text("只支持有效的 HTTPS 地址").font(.footnote).foregroundColor(AppTheme.red) } }.onChange(of: monitor) { _ in store.updateMonitors(store.monitors) } }.onDelete(perform: store.deleteMonitor); Button { store.addMonitor() } label: { Label("添加 HTTPS 监测", systemImage: "plus.circle") }.disabled(store.monitors.count >= 20) } header: { Text("自定义监测 · \(store.monitors.count)/20") } }
    private var backendSection: some View { Section { HStack { Text("后台服务"); Spacer(); Text(store.pluginHealthLabel) }; if let plugin = store.pluginStatus { LabeledContent("累计请求", value: "\(plugin.attempts) 次"); LabeledContent("成功 / 失败", value: "\(plugin.successes) / \(plugin.failures)"); LabeledContent("最近成功", value: clock(plugin.lastSuccessDate)); LabeledContent("最近间隔", value: plugin.lastInterval > 0 ? String(format: "%.1f 秒", plugin.lastInterval) : "--"); LabeledContent("状态来源", value: store.sourceLabel); if let error = plugin.lastError { Text(error).font(.footnote).foregroundColor(AppTheme.amber) } } else { Text("未连接 RootHide DEB；公共状态会回退到 API。").font(.footnote).foregroundColor(AppTheme.secondary) } } header: { Text("后台链路") } }
    private var eventsSection: some View { Section { let events = StatusEngine.loadEvents().prefix(12); if events.isEmpty { Text("暂无异常事件").foregroundColor(AppTheme.secondary) } else { ForEach(Array(events)) { event in HStack(alignment: .top, spacing: 8) { Image(systemName: event.phase == .opened ? "xmark.octagon.fill" : "checkmark.circle.fill").foregroundColor(event.phase == .opened ? AppTheme.red : AppTheme.green); VStack(alignment: .leading) { Text("\(event.target) · \(event.phase == .opened ? "异常" : "恢复")"); Text("\(event.detail) · \(clock(event.date))").font(.footnote).foregroundColor(AppTheme.secondary) } } } } } header: { Text("最近异常事件") } }
    private var aboutSection: some View { Section("关于") { LabeledContent("应用版本", value: "3.4.2 native"); LabeledContent("系统要求", value: "iOS 16.1+"); LabeledContent("Widget", value: "已包含：模型可用性 + 额度"); Link("打开 AI INPUT", destination: gatewayEndpoint) } }
    private func boolBinding(_ keyPath: WritableKeyPath<NotificationSettings, Bool>) -> Binding<Bool> { Binding(get: { store.notificationSettings[keyPath: keyPath] }, set: { value in var settings = store.notificationSettings; settings[keyPath: keyPath] = value; store.updateNotificationSettings(settings); if value { Task { await store.requestNotificationPermission() } } }) }
    private func intBinding(_ keyPath: WritableKeyPath<NotificationSettings, Int>) -> Binding<Int> { Binding(get: { store.notificationSettings[keyPath: keyPath] }, set: { value in var settings = store.notificationSettings; settings[keyPath: keyPath] = value; store.updateNotificationSettings(settings) }) }
}
